### ISSUE TITLE
crashed the app

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022fa-420-C-Sharks#97]
<img width="874" alt="Screen Shot 2022-11-02 at 12 27 12 PM" src="https://user-images.githubusercontent.com/17768351/199546103-3955cd2c-965c-408b-a898-71d181ab9beb.png">

**Comment by smschwartz** [comment]
This happens if there's no json in box

**Comment by Tactical12YearOld** [comment]
Can you please elaborate on this?
Did you do this without signing in? Clicking the editor link in the top nav bar?

**Comment by trevforesta** [comment]
This issue was fixed in later sprint
